In [8]:
import pandas as pd

ntb = pd.read_csv("jumlah_penduduk_nusa_tenggara_barat.csv")

ntt = pd.read_csv("jumlah_penduduk_nusa_tenggara_timur.csv")

nusa_tenggara = pd.concat([
    ntb,
    ntt
])

display(nusa_tenggara)


nusa_tenggara.to_csv(
    'data_penduduk_nusa_tenggara.csv',
    index=False
)

nusa_tenggara.to_json(
    'data_penduduk_nusa_tenggara.json',
    orient='records',
    indent=4
)

total_laki = nusa_tenggara["laki_laki"].sum()
total_perempuan = nusa_tenggara["perempuan"].sum()
total_keseluruhan = nusa_tenggara["total_keseluruhan"].sum()

gabungan = pd.DataFrame([{
    "keterangan": "total_pulau_nusa_tenggara",
    "laki_laki": total_laki,
    "perempuan": total_perempuan,
    "total_keseluruhan": total_keseluruhan
}])


display(gabungan)


gabungan.to_csv(
    'data_gabungan_nusa_tenggara.csv',
    index=False
)

gabungan.to_json(
    'data_gabungan_nusa_tenggara.json',
    orient='records',
    indent=4
)

print("File berhasil disimpan!")

   laki_laki  perempuan  total_keseluruhan
0    2832700    2813300            5646000
0    2871257    2871307            5742564

                  keterangan  laki_laki  perempuan  total_keseluruhan
0  total_pulau_nusa_tenggara    5703957    5684607           11388564

File berhasil disimpan!

In [7]:
import pandas as pd

df = pd.read_csv(
    "Data_Pertumbuhan_Ekonomi_Pulau_Kotor.csv",
    sep=";",
    encoding="latin1",
    on_bad_lines="skip"
)

df = df.iloc[2:, [0, 5]]

df.columns = ["Pulau", "Laju_Pertumbuhan_Ekonomi"]

df = df.dropna()

df = df.reset_index(drop=True)

print(df)

df.to_csv(
    "pertumbuhan_ekonomi_per_pulau.csv",
    index=False
)

df.to_json(
    "pertumbuhan_ekonomi_per_pulau.json",
    orient="records",
    indent=4
)

print("File CSV dan JSON berhasil disimpan!")

                    Pulau Laju_Pertumbuhan_Ekonomi
0                Sumatera                     4,81
1                    Jawa                     5,30
2  Bali dan Nusa Tenggara                     4,87
3              Kalimantan                     4,79
4                Sulawesi                     6,23
5        Maluku dan Papua                     1,44
File CSV dan JSON berhasil disimpan!